<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Log\Controller\IndexController' => __DIR__ . '/src/Log/Controller/IndexController.php',
    'Log\Entity\Log'                 => __DIR__ . '/src/Log/Entity/Log.php',
    'Log\Formatter\Acao'             => __DIR__ . '/src/Log/Formatter/Acao.php',
    'Log\Module'                     => __DIR__ . '/Module.php',
    'Log\Service\Log'                => __DIR__ . '/src/Log/Service/Log.php',
);
